/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_baidu_paddle_lite_demo_ocr_db_crnn_Native */

#ifndef _Included_com_baidu_paddle_lite_demo_ocr_db_crnn_Native
#define _Included_com_baidu_paddle_lite_demo_ocr_db_crnn_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_baidu_paddle_lite_demo_ocr_db_crnn_Native
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_com_baidu_paddle_lite_demo_ocr_1db_1crnn_Native_nativeInit
  (JNIEnv *, jclass, jstring, jstring, jstring, jstring, jstring, jint, jstring);

/*
 * Class:     com_baidu_paddle_lite_demo_ocr_db_crnn_Native
 * Method:    nativeRelease
 * Signature: (J)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_paddle_lite_demo_ocr_1db_1crnn_Native_nativeRelease
  (JNIEnv *, jclass, jlong);

/*
 * Class:     com_baidu_paddle_lite_demo_ocr_db_crnn_Native
 * Method:    nativeProcess
 * Signature: (JIIIILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_baidu_paddle_lite_demo_ocr_1db_1crnn_Native_nativeProcess
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jstring);

#ifdef __cplusplus
}
#endif
#endif
